// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProjectWebView
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIWebViewTestWindow UIWebViewTestWindow
        {
            get
            {
                if ((this.mUIWebViewTestWindow == null))
                {
                    this.mUIWebViewTestWindow = new UIWebViewTestWindow();
                }
                return this.mUIWebViewTestWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIWebViewTestWindow mUIWebViewTestWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIWebViewTestWindow : XamlWindow
    {
        
        public UIWebViewTestWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "WebViewTest";
            #endregion
        }
        
        #region Properties
        public XamlButton UIButtonButton
        {
            get
            {
                if ((this.mUIButtonButton == null))
                {
                    this.mUIButtonButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIButtonButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "buttonTest";
                    #endregion
                }
                return this.mUIButtonButton;
            }
        }
        
        public XamlButton UIButtonButton1
        {
            get
            {
                if ((this.mUIButtonButton1 == null))
                {
                    this.mUIButtonButton1 = new XamlButton(this);
                    #region Search Criteria
                    this.mUIButtonButton1.SearchProperties[XamlButton.PropertyNames.AutomationId] = "buttonTest2";
                    #endregion
                }
                return this.mUIButtonButton1;
            }
        }
        
        public XamlEdit UITxtTestEdit
        {
            get
            {
                if ((this.mUITxtTestEdit == null))
                {
                    this.mUITxtTestEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUITxtTestEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "txtTest";
                    #endregion
                }
                return this.mUITxtTestEdit;
            }
        }
        
        public XamlRadioButton UIRadios2RadioButton
        {
            get
            {
                if ((this.mUIRadios2RadioButton == null))
                {
                    this.mUIRadios2RadioButton = new XamlRadioButton(this);
                    #region Search Criteria
                    this.mUIRadios2RadioButton.SearchProperties[XamlRadioButton.PropertyNames.Name] = " Radios 2";
                    #endregion
                }
                return this.mUIRadios2RadioButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIButtonButton;
        
        private XamlButton mUIButtonButton1;
        
        private XamlEdit mUITxtTestEdit;
        
        private XamlRadioButton mUIRadios2RadioButton;
        #endregion
    }
}
